fix: form field error state checking
valentingavran/anglify pull request #134
Opened 2022-05-11 18:35 UTC by iCrawl

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/valentingavran/anglify/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2022-05-11 18:36 UTC, iCrawl commented
This fixed one point in #133, probably the most crucial one.

Resetting a form now properly removes the displayed errors.

2022-05-12 09:06 UTC, valentingavran requested changes
If we merge this PR, then the following two examples in the documentation will no longer work:
<img width="1125" alt="Bildschirmfoto 2022-05-12 um 11 01 14" src="https://user-images.githubusercontent.com/28765584/168034346-b8cbbf49-083a-42db-a078-1472db63c32a.png">
<img width="1125" alt="Bildschirmfoto 2022-05-12 um 11 01 24" src="https://user-images.githubusercontent.com/28765584/168034355-7d55ef01-cb08-45d2-afa6-5e26adfddd78.png">

Please fix the problem if possible. Otherwise, we will have to look for other solutions.

2022-05-12 15:08 UTC, iCrawl commented
What exactly should happen here, can you explain this a bit further?

The 2nd one works once you touch or make the field non-pristine, which is intended?

2022-05-16 07:49 UTC, valentingavran approved these changes

2022-05-16 07:50 UTC, merged