feat: chip
valentingavran/anglify pull request #150
Opened 2022-05-17 11:07 UTC by sterapps

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ x ] The commit message follows our guidelines: https://github.com/valentingavran/anglify/blob/master/CONTRIBUTING.md#commit
- [ x ] Tests for the changes have been added (for bug fixes / features)
- [ x ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ x ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [ x ] No

2022-05-17 13:15 UTC, iCrawl requested changes

2022-05-17 13:15 UTC, iCrawl commented on apps/docs/src/app/app.module.ts
> +    ChipExamplesModule,
```suggestion
    SnackbarExamplesModule,
    ChipModule,
    ChipExamplesModule,
```

2022-05-17 13:15 UTC, iCrawl commented on apps/docs/src/app/examples/chip/appearances/appearances.component.html
> +<anglify-chip appearance="outlined"> Outlined</anglify-chip>
```suggestion
<anglify-chip appearance="outlined">Outlined</anglify-chip>
```

2022-05-17 13:15 UTC, iCrawl commented on apps/docs/src/app/examples/chip/filter/filter.component.html
> +    <ng-template slot="prepend"> <anglify-icon icon="mdi-home" left></anglify-icon> </ng-template>
```suggestion
    <ng-template slot="prepend">
      <anglify-icon icon="mdi-home" left></anglify-icon>
    </ng-template>
```

2022-05-17 13:15 UTC, iCrawl commented on apps/docs/src/app/examples/chip/filter/filter.component.html
> +    <ng-template slot="prepend"> <anglify-icon icon="mdi-home" left></anglify-icon> </ng-template>
```suggestion
    <ng-template slot="prepend">
      <anglify-icon icon="mdi-home" left></anglify-icon>
    </ng-template>
```

2022-05-17 13:15 UTC, iCrawl commented on libs/anglify/src/modules/chip/_variables.scss
> +$chip-height: var(--anglify-chip-height, 18px);
Per M2 spec, a chip height is 32px.

2022-05-17 13:15 UTC, iCrawl commented on libs/anglify/src/modules/chip/chip-settings.token.ts
> +  size: 'regular',
We shouldn't do different sizes, we also removed this for buttons.

2022-05-17 13:15 UTC, iCrawl commented on libs/anglify/src/modules/chip/chip.interface.ts
> +  size?: ComponentSize;
See above.

2022-05-17 13:36 UTC, iCrawl commented on libs/anglify/src/modules/chip/_variables.scss
> +$chip-background-color: var(--anglify-chip-background-color, var(--color-surface));
```suggestion
$chip-height: var(--anglify-chip-height, 20px);
$chip-background-color: var(--anglify-chip-background-color, var(--color-surface-overlay));
```

2022-05-18 08:09 UTC, iCrawl commented
There still seems to be some sort of conflict here.

2022-05-18 11:52 UTC, iCrawl approved these changes

2022-05-18 14:30 UTC, valentingavran requested changes
Please ensure the following things:

- Add `@HostBinding("tabindex") public tabindex = 0;` to the chip component, so that it can be focused.
- Make sure that the style `&:focus-visible {}` & `&:hover{}` is defined and that the state colors changes with it
- Extract additional CSS variables (like padding  for example)
- Remove the ChipGroup component and use ItemGroup instead in the examples

2022-05-19 10:23 UTC, valentingavran approved these changes

2022-05-19 10:23 UTC, merged